name: "Bug报告"
description: "在使用过程中发现了软件的Bug"
labels: [Bug]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "**我使用的 [MacroER](https://macroer.cubestyle.top) 是最新版本**"
      required: true
    - label: "我已在 [Issues 页面](https://github.com/start1712/MacroER/issues) 中搜索，确认了这一 Bug 未被提交过。"
      required: true
    - label: "我已反复确认此问题长期存在，并不是只出现一次"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 问题描述
    description: "清晰、简洁地描述你遇到的bug是什么，比如：没有按照动作列表运行动作。"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 复现步骤
    description: "一步步写清楚如何复现这个bug，能复现的bug才是能被修复的bug"
    placeholder: "1. 进入页面 xxx
      2. 点击 xxx 按钮
      3. 输入 xxx 内容
      4. 触发 xxx 操作，出现bug"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 预期结果
    description: "你原本期望执行操作后会发生什么，比如：按照动作列表运行动作"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: 实际结果
    description: "实际发生了什么，比如：点没有按照动作列表运行动作"
  validations:
    required: true
- type: textarea
  id: "yml-6"
  attributes:
    label: 补充信息
    description: "用于开发者更好的理解此问题"
    placeholder: "- 截图：粘贴Bug的截图（先点击这个文本框，然后再将文件直接拖拽到文本框中以上传）。
      - 其他：你尝试过的解决方案、是否在其他环境复现等"
  validations:
    required: false